### ISSUE TITLE
[FEATURE] Support for representing objects in the DetectionPointTagGroup

### ISSUE THREAD

**Issue by aas5670** [ADLINK-DEV/ADLINK-VisionDataModels-Reference#14]
**Is your feature request related to a problem or project? Please describe.**
At present, there is no way to represent an object using DetectionPoint's. When adding support for a pose estimation model in deepstream we needed to represent a human using DetectionPoint's.

**Describe the solution you'd like**
We propose to add an optional list of graphs to the DetectionPointTagGroup, each graph will contain nodes that will link DetectionPoint's together with the option for the graph to be directed.

**Comment by geoffmartin-adlink** [comment]
Support added as part of PR #16.
