### ISSUE TITLE
[BUG] Detection Point Tagroup model_id has the wrong type/kind

### ISSUE THREAD

**Issue by RantiE** [ADLINK-DEV/ADLINK-VisionDataModels-Reference#17]
In com.adlinktech.vision.inference/2.2.0/DetectionBoxTagGroup.json the field **model_id** should be type/kind STRING as opposed to STRING_SEQ.

Affected tag Group:
_DetectionPoint::com.adlinktech.vision.inference::2.2.0_

PR for fix: https://github.com/ADLINK-DEV/ADLINK-VisionDataModels-Reference/pull/18

**Comment by geoffmartin-adlink** [comment]
Fixed.
