### ISSUE TITLE
[BUG] tracker_obj_id should be optional

### ISSUE THREAD

**Issue by tobymcclean** [ADLINK-DEV/ADLINK-VisionDataModels-Reference#5]
**Describe the bug**
Not object detection models produce an identifier for the objects detected and track them from one frame to the other. The field will therefore in many situations never be used.

**To Find**
tracker_obj_id - DetectionBoxData:com.adlinktech.vision.inference:2.0

**Expectation **
Changing the **optional** to field to **True**

**Screenshots**
None

**Additional context**
None

**Comment by ronaldvanloonAtADLINK** [comment]
Updated as requested.
