### ISSUE TITLE
[BUG] ClassificationTagGroup has a model_id and ObjectDetectionTagGroup doesn't

### ISSUE THREAD

**Issue by tobymcclean** [ADLINK-DEV/ADLINK-VisionDataModels-Reference#6]
**Describe the bug**
In order to maintain consistency we should keep metadata fields consistent across the inference TagGroups. We have a model_id in the Classification TagGroup but not in the others.

**To Find**
{Classification, Segmentation, DetectionPoint}:com.adlinktech.vision.inference:2.000 vs. {DetectionBox, RawInferenceResult, }:com.adlinktech.vision.inference:2.000.

**Expectation **
All the inference result Tag Groups should have a model_id tag.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by geoffmartin-adlink** [comment]
Raised PR for issue: https://github.com/ADLINK-DEV/ADLINK-VisionDataModels-Reference/pull/11

**Comment by geoffmartin-adlink** [comment]
Addressed by PR #16 .
