### ISSUE TITLE
Type Representation of Tracker-Object and Category Id's

### ISSUE THREAD

**Issue by OctanMan** [ADLINK-DEV/ADLINK-VisionDataModels-Reference#7]
**Describe the bug**
Although we have chosen INT64 to represent tracker-object and category id's, neither Nvidia DeepStream nor OpenVINO/DeepLearningStreamer use this representation in their respective tracker libraries and API's:

DeepStream: https://docs.nvidia.com/metropolis/deepstream/5.0/dev-guide/DeepStream_Development_Guide/baggage/struct__NvDsObjectMeta.html#a05c043991bdf68a50e1844ae92283337
DLS: https://openvinotoolkit.github.io/dlstreamer_gst/classgstgva_1_1tensor_1_1Tensor.html#a0dc226fb3bbd4ae76d33f1e736d87f03

**To Find**
DetectionBox:com.adlinktech.vision.inference:2.000 - DetectionBoxData typedefinition
https://github.com/ADLINK-DEV/ADLINK-VisionDataModels-Reference/blob/master/definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json#L38
https://github.com/ADLINK-DEV/ADLINK-VisionDataModels-Reference/blob/master/definitions/TagGroup/com.adlinktech.vision.inference/2.000/DetectionBoxTagGroup.json#L45

**Expectation**
We propose using STRING type instead to promote explicit conversion from/to these frameworks and others in future. Furthermore, we should standardise an id representation for 'untracked' objects within VisionDataModels.

**Additional context**
This issue was brought to our attention while working with the DetectionBox v1 model and DeepStream. We inadvertently created a bug attempting to assign an UNTRACKED_OBJECT_ID (0xFFFFFFFFFFFFFFFF) value to the INT32 obj_id tag.

**Comment by geoffmartin-adlink** [comment]
Changes made in a forked repository.

PR: https://github.com/ADLINK-DEV/ADLINK-VisionDataModels-Reference/pull/10

**Comment by geoffmartin-adlink** [comment]
Addressed by PR #16 .
